spring.application.name=user-author

server.port=8080
server.servlet.context-path=/jiege

spring.datasource.url=jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=zhang914
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

jwt.secret=f3cb59e9-d541-4e45-9253-1cae096d3a1b
jwt.expire-hours=24